In [1]:
import sklearn

In [2]:
print(sklearn.__file__)

c:\Users\samsung\.venv\Lib\site-packages\sklearn\__init__.py

In [3]:
from sklearn.tree import DecisionTreeClassifier

DecisionTreeClassifier()

DecisionTreeClassifier()

In [12]:
from sklearn.preprocessing import LabelEncoder

items=['mona lisa','van gogh','leonardo da vinci','Mone']
#Captial dfirst, and alphabetical order.
lb_enc=LabelEncoder()
lb_enc.fit(items)
labels=lb_enc.transform(items)
print(labels)

[2 3 1 0]

In [9]:
import seaborn as sb
iris= sb.load_dataset('iris')
iris.head()

items=iris['species']

lb_enc.fit(items)
labels=lb_enc.transform(items)
type(labels)

numpy.ndarray

In [19]:
#inverse transform: index -> original label
#단! out of bound value를 넣으면 곤란하다.

#머신 러닝 이후 서비스할 때 레이블 표시를 위함.

lb_enc.inverse_transform([0,2,1])

array(['Mone', 'mona lisa', 'leonardo da vinci'], dtype='<U17')

In [25]:
lb_enc.fit(iris['species'].unique())
iris['species'].unique()
lb_enc.transform(['abc'])

ValueError: y contains previously unseen labels: 'abc'

In [40]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(-1,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [75]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

#items = [['TV', '냉장고', '전자레인지', '컴퓨터'], ['선풍기', '선풍기', '믹서', '냉장고']]
items=[[1,2,3],[4,5,6]]
print(items)

#2차원 배열로 넣어줘야한다.
#reshape에는 -1을 넣으면 아무거나 들어와도 됨.
#단 parameter의 곱은 전체 shape의 크기와 같아야함.
#따라서 -1,1인 경우, size=6이기 때문에 6*1로 변경됨.
items = np.array(items).reshape(-1,1)
print(items.shape)
print(items)
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

[[1, 2, 3], [4, 5, 6]]
(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

In [ ]:
import pandas as pd
pd.DataFrame(oh_labels.toarray(),columns=oh_encoder.categories_)

#범주형
#명목형 데이터(가전제품 목록)
#bool로 바꿔주는 이유: 값의 크기에 따른 순서가 없기 때문.
#순서형?  (10대,20대, 등급)


#one hot encoding을 사용하는이유가 뭘까?(숙제)
#독립변수(명목형)을 숫자로 변환하기 위함..인데 다른 데이터는 안되는건가?

     1    2    3    4    5    6
0  1.0  0.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0  0.0
4  0.0  0.0  0.0  0.0  1.0  0.0
5  0.0  0.0  0.0  0.0  0.0  1.0

one hot encoding: 
기본적으로 독립변수 -> 2차원 이상의 matrix로 넣어줘야함.


성별,종속변수 -> label encoding으로 진행.

In [83]:
titanic=pd.read_csv('data/titanic.csv')
titanic.head()
sex=titanic['Sex'].to_frame()

In [ ]:
import numpy as np
oh_enc=OneHotEncoder()


oh_sex=oh_enc.fit_transform(sex)
arr=oh_sex.toarray()
print(arr[:-1])

#one hot이 column마다 male, female 1:0이 바뀐다고 하는데
#이게 무슨 말인지 확인하는것이 좋겠다.


titanic['Sex']

[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [1. 0.]
 [0. 1.]]

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: str

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

cat_data=titanic[['Pclass','Sex']]

oh_enc=OneHotEncoder(sparse_output=False)

In [ ]:


lb_enc=LabelEncoder()
res=lb_enc.fit_transform(titanic['Sex'])
res.reshape(-1,1)[:5]

array([[1],
       [0],
       [0],
       [0],
       [1]])

In [133]:
cat_data=titanic[['Pclass','Sex']]
oh_enc=OneHotEncoder(sparse_output=False)
oh_data =oh_enc.fit_transform(cat_data)



#기존 oh_data와 sparse_output=false의 차이가 뭔지 조사하기.

#class A,B,C + female, male matrix를 새로운 column으로 titanic에 추가하기.
titanic[oh_enc.get_feature_names_out()]=oh_data

#아 이걸 matrix으로 바꾸면 데이터를 쓰기 편하겠다.
#어 그런데 pclass와 1,2,3은 같은 데이터라 중복이라 빼 줘야 한댔는데!!

#one hot encoding의 목적이 뭐였더라..?

titanic = titanic.drop(['Pclass','Sex'],axis=1)
#inplace 사용시 바로 titanic에 반영됨.

In [ ]:
oh_data.dtype

,PassengerId,Survived,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,a,b,c,d,e,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male
0,1,0,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,S,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,C,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,3,1,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,S,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
4,5,0,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,S,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,"Montvila, Rev. Juozas",27.0,0,0,211536,13.0000,NaN,S,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
887,888,1,"Graham, Miss. Margaret Edith",19.0,0,0,112053,30.0000,B42,S,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
888,889,0,"Johnston, Miss. Catherine Helen ""Carrie""",NaN,1,2,W./C. 6607,23.4500,NaN,S,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
889,890,1,"Behr, Mr. Karl Howell",26.0,0,0,111369,30.0000,C148,C,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
890,891,0,"Dooley, Mr. Patrick",32.0,0,0,370376,7.7500,NaN,Q,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0

dtype이 float인 이유
1. numpy=series= 그냥 array라고 생각하기.
2. 1개의 배열은 모두 동일한 자료형을 가져야한다.
3. 왜 int를 넣지 않았을까?
4. class와 sex의 경우 변환 과정에서 숫자로 변환되었다.
5. 이 과정에서 float가 하나라도 있었다면, 모든 data가 float로 변환된다 (왜냐하면 float가 int보다 크기 때문에,
float value 1개가 truncated 되는 것을 막기 위해.)

6. 근데 그러면 메모리 낭비가 좀 클 거 같다.

7. data frame은 컬럼별로 구분이 되기 때문에, 이런 면에서 사용하기 편하다.

In [147]:
titanic=pd.read_csv('data/titanic.csv')
titanic=titanic.drop(['Name','Ticket','Cabin'],axis=1)

pd.get_dummies(titanic)

titanic['Embarked']
# titanic[titanic['Embarked']==None]



#명목형 데이터 str을 -> true false 데이터로 변환하는 것.
# + 테이블에 추가해주기
#+ 기존 sex 명목형 데이터 행 제거.

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

범주형 데이터: 문자로 표현된 성별,남녀 등.

숫자로 표현된 범주형 데이터는???
get_dummies는 문자로 된 데이터만 처리함.